#+TITLE: Deferred Data Structures supporting Rank, Select in MultiSets
#+DESCRIPTION: Implementations and Experimentations on Deferred Data Structures supporting Rank, Select in MultiSets
#+AUTHOR: Jérémy Barbay
#+EMAIL: jeremy@barbay.cl
#+CATEGORY: Research

* Introduction
** Theory
*** Static Content

Given a \textsc{Multiset} $W[1..n]$ on alphabet $[1..\sigma]$ of size $n$, Karp et al. [SJC 1988] defined the first deferred data structure supporting for all $x\in[1..\sigma]$ and $r\in[1..n]$ queries such as \texttt{rank}$(x)$, the number of elements which are strictly smaller than $x$ in $W$; and \texttt{select}$(r)$, the value of the $r$-th smallest value (counted with multiplicity) in $W$.  Their data structure supports $q$ queries in time within $O(n(1+\lg q)+q\lg n)$, all in the comparison model, which is the minimum amount of work in the worst case over instances of multiset size $n$ and query number $q$ fixed (i.e. the query size). 

Barbay et al. [ESA 2013] refined this approach to take advantage of the gaps between the positions hit by the queries (i.e. the structure of the queries).  Their data structure is simpler (a single binary array) and their analysis is finer, taking into account the gaps between the position hit by the queries.

*** Dynamic content

Barbay et al. (WALCOM 2014) extended those results to the dynamic version of the \emph{online multiselection} problem for internal and external memory, in which~$q$ selection queries are requested on an unsorted array of $N$~elements. Their internal memory result is $1$-competitive with the offline result of Kaligosi et al.  [ICALP 2005].  In particular, they extend the results of Barbary et al.  [ESA 2013] by supporting arbitrary \emph{insertions} and \emph{deletions} while supporting online \emph{select} and \emph{search} queries on the array. Assuming that the insertion of an element is immediately preceded by a search for that element, they showed that their dynamic online algorithm performs an optimal number of comparisons, up to lower order terms and an additive~$O(N)$ term.

*** In External Memory

For the external memory model, they described the first online multiselection algorithm that is $O(1)$-competitive, and showed how to support searches, insertions, and deletions of elements efficiently.  This result improves upon the work of Sibeyn [JoA 2006] when $q > m$, where $m$ is the number of blocks that can be stored in main memory.

** Experimentations

It is not clear whether Karp et al. [JC 1988] nor Ching et a. [IPL 1990] implemented the defferred data structure that they described. [CHECK Kurt Mehlhorn's webpage for available code?]

Barbay et al. [ESA 2013] experimental results comparing online and offline algorithms. Their experimental results show that their online algorithms require fewer comparisons than the best-known offline algorithms. Interestingly, their experiments suggest that the optimal online algorithm (when used to sort the array) requires fewer comparisons than both quicksort and mergesort.  They implemented randomized variants in C and in java, but did not distribute their code.
* Proposal

We propose to gather in this open source project an open source library of implementations of Deferred Data Structures for Multisets, in order to
1. facilitate the comparison of new implementations of such deferred data structures with existing ones, and to
2. facilitate the use of those data structures in other projects, whether for research or for practical purpose.

For those purpose, the project is divided in two parts, one relevant to the implementation of deferred data structures for multisets, and one relevant to their evaluation:

** Implementations 
The folder [[file:Implementations][file:Implementations]] contains various implementations of Deferred Data Structures for Multisets, in [[file:Implementations/C/][C]], [[file:Implementations/Java][Java]] and [[file:Implementations/Python][python]].

*** Greedy Implementation in Python
The project is initiated with a greedy implementation in Python in [[file:Implementations/Python/greedyImplementation.py][file:Implementations/Python/greedyImplementation.py]] of the fonctionalities of a deferred data structure, which can be used as a reference for checking the correction of more sophisticated implementations. 
*** Pivot Array based implementation in Python
*** Pivot Array based implementation in C
*** Pivot Array based implementation in Java


** Evaluation
A folder containing various scripts, programs and data for the evaluation and comparison of the performance of Deferred Data Structures


* List of methods
  Each Deferred Data Structure implementation must implement the class =PartiallySortedArray=, which the following methods:

    1. [ ] =__init__(A)= which receives as input an array of comparable values (e.g. integers), and return the corresponding deferred data structure.
    2. [ ] =__len__()= which returns the number of elements in the Partially Sorted Array.
    3. [ ] =select(r)= which returns the element of the set such that r elements are smaller.
    4. [ ] =rank(x)= which returns the number of elements in the set which are smaller than x.
    5. [ ] =rankRight(x)= which returns the number of elements in the set which are smaller than or equal to x.
    6. [ ] =totalNbOfQueriesPerformed()=, which returns the total number of queries performed on the Partially Sorted Array.

  The file [[file:Implementations/Python/greedyImplementation.py][file:Implementations/Python/greedyImplementation.py]] is a good example of a greedy implementation in python of a deferred data structure supporting those methods.

